---
abstract: 'KyotoTycoon client library'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  File::Which: 0
  Test::More: 0.98
  Test::Requires: 0
  Test::TCP: 1.17
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-KyotoTycoon
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Cache::KyotoTycoon:
    file: lib/Cache/KyotoTycoon.pm
    version: 0.14
  Cache::KyotoTycoon::Cursor:
    file: lib/Cache/KyotoTycoon/Cursor.pm
    version: 0
  TSVRPC::Client:
    file: lib/TSVRPC/Client.pm
    version: 0.01
  TSVRPC::Parser:
    file: lib/TSVRPC/Parser.pm
    version: 0
  TSVRPC::Util:
    file: lib/TSVRPC/Util.pm
    version: 0
requires:
  Exporter: 0
  Furl: 1.00
  MIME::Base64: 0
  MIME::QuotedPrint: 0
  URI::Escape: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
